### ISSUE TITLE
Installs all the dev dependencies when publishing

### ISSUE THREAD

**Issue by vibecode-zz** [debashish2014/local-package-publisher#2] opened 2021-06-24 15:34 UTC
**Actual behavior:** 
With package.json looking similiar to this: 

```{
  "name": "@mynamespace/mypackage",
  "description": "....",
  "version": "1.0.0",
  "main": "dist/index.js",
  "module": "dist/index.es.js",
  "files": [
    "dist"
  ],
  "peerDependencies": {
    "classnames": "^2.2.6",
    "dinero.js": "^1.8.0",
    "@material-ui/core": "^4.9.5",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.46",
     .........
  },
  "devDependencies": {
    "classnames": "^2.2.6",
    "dinero.js": "^1.8.0",
    "axios": "^0.21.1",
    "prop-types": "^15.7.2",
    "react-responsive": "^8.2.0",
    "lodash.throttle": "^4.1.1",
    "js-cookie": "^2.2.1",
    "moment": "^2.28.0",
    "react-html-parser": "^2.0.2",
     "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-i18next": "^11.8.5",
    "react-responsive": "^8.2.0",
     .......
```

it seems to be installing all the dev dependencies when publishing.

**Expected behavior**: install only peers if missing.

**Comment by debashish2014** [comment] 2023-06-21 19:11
Hi @vibecode, the tool relies on the `npm link` in the target project where we want to consume the published package. 

I tried to reproduce the issue by publishing a react icons library using version 1.0.5 and tried to consume it in a barebones node js project with just 2 files, index.js, and package.json( created with node init). It did not install any dev dependencies. But the fact is it did not install any peers as well.

Looks like the npm link works this way.

I just wanted to let you know that I'm closing this issue for now.

**Closed as completed by debashish2014** 2023-06-21 19:11 UTC
